[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/test-db"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
[deploy.variables]
DATABASE_URL = postgresql://postgres:fMyKFGTAAxRUCiVtbEImKLHtzrIlThtV@postgres.railway.internal:5432/railway
NEXTAUTH_URL = neko-scans.up.railway.app
NEXTAUTH_SECRET = mRVTFz+MuCQzcj+Z7//N3J6sO33P8UoJ0djK8uMyzjA=
NODE_ENV = "production"
